name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.5
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run
      run: go run . --maxTurns=20 # fight OOM error
    - name: Output output.json
      run: cat output/output.json
    - name: Install yarn 
      run: npm i -g yarn        
    - name: Cache node_modules #speed things up significantly
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - name: Install Dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: |
        cd website
        yarn install      
    - name: Build website
      run: |
        cd website
        yarn build
        test -f build/index.html
    - name: Deploy website
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        build_dir: website/build
        branch: gh-pages