name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.5
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run
      run: sudo go run .
    - name: Build website
      run: |
        cd website
        npm i -g yarn
        yarn install
        yarn build
    - name: Deploy website
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages 
        FOLDER: website/build 
        CLEAN: true
      
    