name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.5
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run
      run: sudo go run .
    - name: Build and deploy website
      run: |
        cd website
        npm i -g yarn
        yarn install
        yarn build
        yarn deploy
      
    